# 基本配置
server:
  port: 8080
  context-path: /

# 自定义配置
app:
  crypto:
    # 是否启用加密
    status: false
    # 密钥文件位置
    rsa-public: classpath:crypto/public.key
    rsa-private: classpath:crypto/private.key
  # 配置数据源
  datasource:
    # 基本数据库信息
    url: jdbc:mysql://x.x.x.x/car?useUnicode=true&characterEncoding=utf-8
    username: xxx
    password: xxx
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 2
    max-active: 20
    min-idle: 0
    max-wait: 60000
    validation-query: SELECT 1
  # mybatis配置
  mybatis:
    # 因为不同包下可能有类名相同的实体类，所以官方并没有支持
    # type-aliases-package: 修改DataSourceConfig中的getMybatisTypeAliasesPackage()即可
    config-location: classpath:mybatis-config.xml
    mapper-locations: classpath:mapper/**/*.xml