# 自定义配置
app:
  crypto:
    # 是否启用加密
    status: true
    # 密钥文件位置
    rsa-public: classpath:crypto/public.key
    rsa-private: classpath:crypto/private.key

# spring的配置
spring:
  # 配置数据源
  datasource:
    # 基本数据库信息
    url: jdbc:mysql://x.x.x.x/xxx?useUnicode=true&characterEncoding=utf-8
    # xxx
    username: xxx
    # xxx
    password: xxx