# 基本配置
server:
  port: 8080
  context-path: /

# 自定义配置
app:
  crypto:
    # 是否启用加密
    status: true
    # 密钥文件位置（建议放在非项目目录下,且使用绝对路径）
    rsa-public: E:/Temps/public.key
    rsa-private: E:/Temps/private.key
  # 配置数据源
  datasource:
    # 基本数据库信息
    url: jdbc:mysql://x.x.x.x:xxxx/car?useUnicode=true&characterEncoding=utf-8
    # RSA公钥加密的
    username: xxx
    # RSA公钥加密的
    password: xxx
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 2
    max-active: 20
    min-idle: 0
    max-wait: 60000
    validation-query: SELECT 1
  # mybatis配置
  mybatis:
    # 生产环境下不会加载test功能
    config-location: classpath:mybatis-config.xml
    # 注意少了一个星号
    mapper-locations: classpath:mapper/*.xml