# 自定义配置
app:
  crypto:
    # 是否启用加密
    status: true
    # 密钥文件位置
    rsa-public: classpath:crypto/public.key
    rsa-private: classpath:crypto/private.key

# spring的配置
spring:
  # 配置数据源
  datasource:
    # 基本数据库信息
    url: jdbc:mysql://192.168.56.2/test?useUnicode=true&characterEncoding=utf-8
    # chain
    username: YbKJaJzC4HNYgqwtOzAsi6GLK92953jTIVYnu9AZyOp7JrVS5y7HKrw/ks9urdbRU6oFRvd1ahbL
              PwXyOJKLyzBgKc4LyvlriomDxSLCrkMcKXbxs3rW2rB5i/x8TuFi9nugmktgc3UplcwBZ3IjJYOW
              OTE7pDG6ga9K5OykvMc=
    # 0702
    password: F+knZXWvyJzVm6d0m/pWTtzrpcqBd6ilTBoZbi5HQVAetvmcGn+6+XQHGAB6jmCpgAUMvjTiuoSl
              Kb0ohRKwrby1ArTIbIdcYE0V3U/12c3QXwsBQLhm5xQ4sNfH5DV/AJc7wr5obV58CdEnWTySY/6A
              tEJbg+HQ/wRvb+M2UG8=