# 自定义配置
app:
  crypto:
    # 是否启用加密
    status: false
    # 密钥文件位置
    rsa-public: classpath:crypto/public.key
    rsa-private: classpath:crypto/private.key

# spring的配置
spring:
  # 配置数据源
  datasource:
    # 基本数据库信息
    # 如果密码是纯数字需要加上引号
    url: jdbc:mysql://192.168.56.2/test?useUnicode=true&characterEncoding=utf-8
    username: chain
    password: "0702"

