# 自定义配置
app:
  crypto:
    # 是否启用加密
    status: true
    # 密钥文件位置
    rsa-public: classpath:crypto/public.key
    rsa-private: classpath:crypto/private.key

# spring的配置
spring:
  # 配置数据源
  datasource:
    # 基本数据库信息
    url: jdbc:mysql://192.168.56.2/test?useUnicode=true&characterEncoding=utf-8
    # chain
    username: wudjGhgBt+c+3Ncf2VVvhflph/6h9Ukd/agHNWG+ESwA9TFvOUGrMAH07mdJH+g/np/PZqZKIvxp
              vA5fQsEPsQMPjpBLJkY/Hl9x8Rb0pfXvKw3CZOAn4nsZpIZfxyCWFafUG3xTXM03zm7yvZENcqFs
              BzQs1sEp2RYrumX01/o=
    # 0702
    password: DfS6qsq8GSUI4BUESV8RAQ+oRQxZ4GeoYwN+NPIeFczLM8nqXizsnDmmcCVZ6rPOUad02cz5nnxW
              7ULtCm7LfcqIe9pTz3SdKalF46NMYiASAoBTpqf8q8NdXRa1+Y+YFmW3HVrt8x8umvq+PxXzzbFJ
              4r3ucC7O5gol/1RTIaA=