# 自定义配置
app:
  crypto:
    # 是否启用加密
    status: true
    # 密钥文件位置（建议放在非项目目录下,且使用绝对路径）
    rsa-public: E:/Temps/public.key
    rsa-private: E:/Temps/private.key

# spring的配置
spring:
  # 配置数据源
  datasource:
    # 基本数据库信息
    url: jdbc:mysql://localhost:3306/xxx?useUnicode=true&characterEncoding=utf-8
    # RSA公钥加密的
    username: xxx
    # RSA公钥加密的
    password: xxx